from __future__ import annotations

from core.models import InsightStatus


INSIGHT_STATUS_COLORS = {
    InsightStatus.QUEUED.value: "#8A8F98",
    InsightStatus.RUNNING.value: "#0078D4",
    InsightStatus.DONE.value: "#107C10",
    InsightStatus.WARNING.value: "#C19C00",
}

INSIGHT_PANEL_DARK_BACKGROUND = "#202020"
INSIGHT_PANEL_DARK_BORDER = "#3d3d3d"
INSIGHT_PANEL_DARK_EMPTY_TEXT = "#c9c9c9"
INSIGHT_PANEL_LIGHT_BACKGROUND = "#ffffff"
INSIGHT_PANEL_LIGHT_BORDER = "#d8dde6"
INSIGHT_PANEL_LIGHT_EMPTY_TEXT = "#5f6670"

PROJECT_SOURCE_LIST_DARK_BACKGROUND = "#2b2b2b"
PROJECT_SOURCE_LIST_DARK_BORDER = "#3d3d3d"
PROJECT_SOURCE_LIST_DARK_TEXT = "#f1f1f1"
PROJECT_SOURCE_LIST_DARK_ALTERNATE_BACKGROUND = "#303030"
PROJECT_SOURCE_LIST_DARK_SELECTED_BACKGROUND = "#005fb8"
PROJECT_SOURCE_LIST_DARK_SELECTED_TEXT = "#ffffff"
PROJECT_SOURCE_LIST_LIGHT_BACKGROUND = "#ffffff"
PROJECT_SOURCE_LIST_LIGHT_BORDER = "#d8dde6"
PROJECT_SOURCE_LIST_LIGHT_TEXT = "#202020"
PROJECT_SOURCE_LIST_LIGHT_ALTERNATE_BACKGROUND = "#f6f8fb"
PROJECT_SOURCE_LIST_LIGHT_SELECTED_BACKGROUND = "#dbeafe"
PROJECT_SOURCE_LIST_LIGHT_SELECTED_TEXT = "#1a1a1a"

SPLASH_LOADER_TRACK_LIGHT_RGBA = (118, 185, 237, 46)
SPLASH_LOADER_TRACK_DARK_RGBA = (96, 205, 255, 52)
SPLASH_LOADER_ARC_LIGHT_RGB = (0, 120, 212)
SPLASH_LOADER_ARC_DARK_RGB = (96, 205, 255)

SPLASH_DARK_CARD_BACKGROUND = "rgba(31, 31, 31, 246)"
SPLASH_DARK_CARD_BORDER = "rgba(96, 205, 255, 58)"
SPLASH_DARK_TITLE_TEXT = "#f3f6fa"
SPLASH_DARK_SUBTITLE_TEXT = "#c8cdd4"
SPLASH_DARK_STATUS_TEXT = "#8fdcff"
SPLASH_DARK_PROGRESS_BACKGROUND = "rgba(96, 205, 255, 36)"
SPLASH_DARK_PROGRESS_CHUNK = "#60cdff"
SPLASH_LIGHT_CARD_BACKGROUND = "rgba(250, 252, 255, 244)"
SPLASH_LIGHT_CARD_BORDER = "rgba(0, 120, 212, 52)"
SPLASH_LIGHT_TITLE_TEXT = "#162033"
SPLASH_LIGHT_SUBTITLE_TEXT = "#5c6470"
SPLASH_LIGHT_STATUS_TEXT = "#2f5f8f"
SPLASH_LIGHT_PROGRESS_BACKGROUND = "rgba(0, 120, 212, 34)"
SPLASH_LIGHT_PROGRESS_CHUNK = "#0078d4"
