"""Shared runtime application metadata."""

APP_NAME = "CharaPicker"
APP_ORGANIZATION_NAME = APP_NAME
APP_VERSION = "0.3.0"
APP_RELEASE_STAGE = "alpha"
APP_VERSION_TAG = f"{APP_VERSION}-{APP_RELEASE_STAGE}" if APP_RELEASE_STAGE else APP_VERSION

HTTP_USER_AGENT = f"{APP_NAME}/{APP_VERSION_TAG}"
